services:
  frontend:
    build:
      context: ./front_pp_01 
    ports:
      - "3000:3000"
    volumes:
      - ./front_pp_01:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WATCHPACK_INTERVAL=1000
  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: db_manage_rpg
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abc123
    ports:
      - "5432:5432"
volumes:
  db_data:
  # backend:
  #   build:
  #     context: ./back_pp_01
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./back_pp_01:/app
  #   environment:
  #     - ASPNETCORE_ENVIROMENT=development
  