services:
  frontend:
    build:
      context: ./front_pp_01 
    ports:
      - "3000:3000"
    volumes:
      - ./front_pp_01:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  # backend:
  #   build:
  #     context: ./back_pp_01
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./back_pp_01:/app
  #   environment:
  #     - ASPNETCORE_ENVIROMENT=development